const cities = {
  ARQ: "Araraquara - ARQ",
  AVR: "Avaré - AVR",
  BRT: "Barretos - BRT",
  BRI: "Birigui - BRI",
  BTV: "Boituva - BTV",
  BRA: "Bragança Paulista - BRA",
  CMP: "Campinas - CMP",
  CJO: "Campos do Jordão - CJO",
  CPV: "Capivari - CPV",
  CAR: "Caraguatatuba - CAR",
  CTD: "Catanduva - CTD",
  CBT: "Cubatão - CBT",
  GRU: "Guarulhos - GRU",
  HTO: "Hortolândia - HTO",
  ISA: "Ilha Solteira - ISA",
  ITP: "Itapetininga - ITP",
  ITQ: "Itaquaquecetuba - ITQ",
  JCR: "Jacareí - JCR",
  JND: "Jundiaí - JND",
  MTO: "Matão - MTO",
  PRC: "Piracicaba - PRC",
  PII: "Pirituba - PII",
  PEP: "Presidente Epitácio - PEP",
  RGT: "Registro - RGT",
  SLT: "Salto - SLT",
  SCL: "São Carlos - SCL",
  SBV: "São João da Boa Vista - SBV",
  SJC: "São José dos Campos - SJC",
  SAM: "São Miguel Paulista - SAM",
  SPO: "São Paulo - SPO",
  SRQ: "São Roque - SRQ",
  SRT: "Sertãozinho - SRT",
  SOR: "Sorocaba - SOR",
  SZN: "Suzano - SZN",
  TUP: "Tupã - TUP",
  VTP: "Votuporanga - VTP"
};

export default cities;
